### ISSUE TITLE
App can't be open [MacBook Pro M1Max]

### ISSUE THREAD

**Issue by sonalder-darlene** [amo13/Anarchy-Droid#28]
After installing the app it refuse to launch, maybe due to my M1 chip. Is this a known issue ?

**Comment by amo13** [comment]
No, the issue was not yet known, thank you for reporting it!
It might very well have something to do with the M1 chip, or at least I observe that nearly every software has to be updated in some way to work on the M1 MacBooks...
I just updated all dependencies and triggered a recompilation. That might already help solve the issue. Could you please try with the following version:
[Anarchy-Droid (MacOS).zip](https://github.com/amo13/Anarchy-Droid/files/8577632/Anarchy-Droid.MacOS.zip)
[Anarchy-Droid_darwin_amd64.zip](https://github.com/amo13/Anarchy-Droid/files/8577633/Anarchy-Droid_darwin_amd64.zip)

If it still doesn't work, I'd be thankful if you could launch the app from a terminal, so we can see some debugging output. Otherwise, I cannot know where to look for a solution.

**Comment by sonalder-darlene** [comment]
Impossible to open Anarchy-Droid

**Comment by amo13** [comment]
I'd like to help, but I need more detail:

> If it still doesn't work, I'd be thankful if you could launch the app from a terminal, so we can see some debugging output. Otherwise, I cannot know where to look for a solution

**Comment by dlly11** [comment]
Hi,

I compiled this on an M2 MacBook Air - 2022 model. I was able to open the app with no issues - I haven't tested anything with regards to functionality other than opening the application. 

I am not at all familiar with Go or it's toolchains. Can you just cross compile it with an Arm toolchain?

**Comment by amo13** [comment]
Just like in #36, hopefully this is now fixed. Please reopen if not.
