### ISSUE TITLE
Installing Lineage OS on Galaxy A52

### ISSUE THREAD

**Issue by IdleEndeavor** [amo13/Anarchy-Droid#29]
Hey there

I have a Samsung Galaxy A52 device and I've come across a well maintained unofficial Lineage OS release on XDA forums.
When using Anarchy-Droid (Fedora Linux), it's just stuck on "Trying to Recognize the Device'. 
I've heard stuff about needing something called Odin to install custom ROMs on Samsung devices and stuff. I have no idea about how or what any of this is, therefore I might be the target audience of Anarchy-Droid. 

Can someone help me please?

Thanks a lot for your works,
Regards

**Comment by amo13** [comment]
Yes, you can use Odin to install twrp, which is needed to then install LineageOS. But heimdall should work too instead of Odin and Anarchy-Droid uses heimdall in the background.

I'll take a look at what might cause the device recognition problem.

Meanwhile, could you please drop a link here to the unofficial lineage release?

**Comment by IdleEndeavor** [comment]
https://forum.xda-developers.com/t/unofficial-rom-12-0-lineageos-19-0-for-a52-4g-and-a72.4364519/

My device to be exact is the: Samsung Galaxy A52 4G, SM-A525F/DS

**Comment by amo13** [comment]
Thanks for the info!
I have not added the rom to the Anarchy-Droid archive for selection in the app because of the three things still marked as bugs by the rom maintainer. Still, you can download the rom zip and select it inside Anarchy-Droid.
I added "SM-A525F/DS" to the device recognition database. Please try again now.

Note that there is no official OpenGapps package published yet for Android 12 (LineageOS 19), so if you need Gapps, Anarchy-Droid cannot take care of that. 

Also note that heimdall is somewhat old software and might not be able to flash TWRP in the first step on your device because it is a very recent device and heimdall is known to be incompatible with newer devices. But you might be lucky, just try it out and feel free to report back here!

**Comment by IdleEndeavor** [comment]
What happens if it doesn't flash in the first try? I'm new to this so am a bit scared, sorry about that.
Also, since you've gone through the XDA page, I'm hoping there are no other requirements that need to be met for flashing the ROM.

**Comment by amo13** [comment]
I have flashed a lot of devices and in my experience, if a flashing does not work, then nothing happens and you might only need to reboot the phone. For this, there is always a hardware key combination, like Home + Power + Vol-Up for 5 seconds or so...
In the worse case, for some reason the procedure only goes half through and you find yourself with a device reset to factory settings.

**Comment by IdleEndeavor** [comment]
I see, the time is just right then.
I'm going to be giving my smartphone for repairs and Samsung will be resetting it anyway.
So I will try to flash it when I receive it back.

However , I wanted to know about updates. Since OTA updates aren't available for unofficial ROMs, how do I go about applying new updates without resetting the phone?

**Comment by amo13** [comment]
yes, try after receiving it back, since your warranty might be considered void after flashing a custom rom.

You could go about updating with Anarchy-Droid. You'll just want to tick the box "Do not wipe the data partition" under advances settings.

**Comment by IdleEndeavor** [comment]
Hey there,
Sorry for messaging again.
In case I want to revert back to original OneUI, how do I do that?
ALso, the XDA page mentioned something about a *VMBeta Disabler*, I am unaware of what that is

**Comment by amo13** [comment]
I think reverting back to the OneUI stock rom might be a little more complicated. You might need to actually use odin or find out how to do this with heimdall. I'd look for a tutorial on xda for this. That being said, I have never needed to return to a stock rom on any device I have flashed. 

> ALso, the XDA page mentioned something about a VMBeta Disabler, I am unaware of what that is

I have never used that and for me everything always worked fine. Yet, I have never flashed a device as recent as yours. From what I can see, there are people who say that one should flash vbmeta (disabling oem keys for partition verification) and others who say that vbmeta is disabled automatically once you hit the "oem unlock" switch in the developer settings. For your device, I don't know.
